name = 'LGFXtheme'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'A custom theme for LiminalGFX.com'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/owner/repo'

# If you have a running demo of the theme
demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['portfolio', 'LiminalGFX']
features = ['mason grid', 'fancybox', 'portfolio']

# If the theme has a single author
[author]
  name = 'Daniel Nagy'
  homepage = 'LiminalGFX.com'